#!/usr/bin/env bash
#Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.html

#REDIRECTION
#CREATE FOLDER REDIRECTION 404
sudo mkdir /var/www/error
echo "Ceci n'est pas une page" > /var/www/error/404.html
sudo sed -i "s|server_name\ _;|server_name _;\n\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default
#REDIRECTION 404 Page
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default
sudo service nginx restart