#!/usr/bin/env bash
#script that configures an Ubuntu server
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/Test
sed -i s/127.0.0.1/127.0.0.2/  ~/Test
echo "8.8.8.8 facebook.com" >> ~/Test
cp -f ~/Test /etc/hosts

